### ISSUE TITLE
Why stop_queries uses working_ind to update itself before updating working_ind?

### ISSUE THREAD

**Issue by machanic** [uclaml/RayS#1]
Why line https://github.com/uclaml/RayS/blob/master/RayS.py#L63 is before https://github.com/uclaml/RayS/blob/master/RayS.py#L64, rather than after line 64?
It means the `working_ind` is not updated in updating stop_queries.

**Comment by uclaml** [comment]
stop_queries aims to measure the number of queries needed until the first time we found a successful attack (note that we can still continue performing RayS to get better decision boundary estimates), so it is different from the final number of queries. In this regard, we update the stop_queries for all working_ind each time and stop updating them once they are not in working_ind (success attack found). Hope this answers your question.

**Comment by machanic** [comment]
@uclaml Why you place `working_ind = (dist > self.epsilon).nonzero().flatten()` **after** `stop_queries[working_ind] = self.queries[working_ind]`???  Isn't it to be **placed before** `stop_queries[working_ind] = self.queries[working_ind]`?

**Comment by uclaml** [comment]
A simple counterexample: assume it works in the order you said. stop_queries is initialized as a zero vector and working_ind is an all-one vector. Suppose in the first attempt we successfully attacked all indices, meaning dist<=epsilon for all indices.  Now you will first update working_ind to be an empty list and therefore there will be no update on stop_queries (remains zero vector). Yet this is not correct, as the stop_queries should be the queries used in the first attempt. Hope this helps.
